### PR TITLE
Set SDK to 3.32

### PR DESCRIPTION
**Pull request by hfiguiere**
Since the upgrade to 3.34 seems to be running into problems (see issue #5) let's at least update to 3.32.

### CODE REVIEW

**Comment by hfiguiere** [comment]
Prediction, the appdata will not validate. *sigh*

**Comment by bilelmoussaoui** [comment]
It will as elementary enforce the same rules as Flathub +/-

**Comment by TingPing** [comment]
Oh I just realized you use the wrong baseapp, so fixing that might help?

**Comment by bilelmoussaoui** [comment]
@TingPing Well spotted. Will give it a try now

**Comment by hfiguiere** [comment]
you meant for issue #5 ?

**Comment by bilelmoussaoui** [comment]
Done https://github.com/flathub/com.github.calo001.fondo/pull/7

**Pull request merged**
